version: '3.8'
services:
  mssql_service:
    build:
      context: db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "tickets@@pa55W0rd"
      MSSQL_PID: "Evaluation"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./db/dbo/tables:/docker-entrypoint-initdb.d
      - ./db/dbo/scripts:/docker-entrypoint-initdb.d/seed
    container_name: mssql_service
    hostname: sqlpreview
    restart: unless-stopped

  api_service:
    image: ticketsservice
    build:
      context: .
      dockerfile: Dockerfile

volumes:
  sqlserver_data:
