apiVersion: v1
kind: PersistentVolume
metadata:
  name: my--cypress-reports-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "D:/kubernetes/e2e-test/cypress"
    # Replace with your local path
---

apiVersion: batch/v1
kind: Job
metadata:
  name: cypress-test-test-test
  labels:
    app: cypress-first-test
spec:
  # replicas: 1
  # selector:
  #   matchLabels:
  #     app: cypress
  template:
    metadata:
      name: cypress-first-test
      # labels:
      #   app: cypress
    spec:
      containers:
        - name: cypress-first-test
          image: fideliswaweu19/e2e-app-test
          volumeMounts:
            - name: cypress-first-test-pv
              mountPath: /app/cypress/reports
          ports:
            - containerPort: 80
          imagePullPolicy: IfNotPresent
      volumes:
        - name: cypress-first-test-pv
          persistentVolumeClaim:
            claimName: cypress-first-test-pvc
      restartPolicy: OnFailure

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cypress-first-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: e2e-test-app
#   labels:
#     app: e2e-test-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: e2e-test-app
#   template:
#     metadata:
#       name: e2e-test-app
#       labels:
#         app: e2e-test-app
#     spec:
#       containers:
#         - name: e2e-test-app
#           image: fideliswaweu19/cypress-test
#           ports:
#             - containerPort: 80
#           imagePullPolicy: IfNotPresent
#       restartPolicy: Never
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: e2e-test-app
# spec:
#   selector:
#     app: e2e-test-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: NodePort