name: ci

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          path: .github/workflows/

      - name: List directory contents
        run: ls -la

#      - name: Restore dependencies
#        run: dotnet restore
#        working-directory: ./ticketsservice
#
#      - name: Build
#        run: dotnet build --no-restore
#        working-directory: ./ticketsservice
