name: ci

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          path: .github/workflows/

      - name: List directory contents
        run: pwd

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
