name: Build .NET App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: List files
        run : |
          ls -la
          
          
      - name: Print Runner IP
        run: |
          echo "IP address of the current GitHub runner:"
          host $(hostname)
          
#      - name: Build Docker image
#        run: |
#          docker build -t muhohoweb/tickets-service:1.0.5 .
#          docker images
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v1
#        with:
#            username: ${{ secrets.DOCKER_HUB_USERNAME }}
#            password: ${{ secrets.DOCKER_HUB_TOKEN }}
#
#      - name: Push Docker image to Docker Hub
#        run: |
#          docker push muhohoweb/tickets-service:1.0.5

      - name: Install VPN client
        run: |
            # Example: Install VPN
            sudo apt update
            sudo apt install -y openvpn openvpn-systemd-resolved  # For Ubuntu/Debian
          
      - name: Connect to VPN
        run: |
          # Write client certificate to file
          echo "${{ secrets.VPN_CLIENT_CERT }}" > client.crt
          # Write client private key to file
          echo "${{ secrets.VPN_CLIENT_KEY }}" > client.key
          
          # Write OPEN_VPN private key to file
          echo "${{ secrets.OPEN_VPN }}" > config.ovpn
          
          ls -la
          # Command to connect to VPN using certificates
          sudo openvpn --config config.ovpn --cert client.crt --key client.key --verb 3
      - name: Ping Private Instances
        run: |
          # Ping private instances
          ping 10.0.141.195

