name: Build .NET App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: List files
        run : |
          ls -la
          
      - name: Build Docker image
        run: |
          docker build -t muhohoweb:ticketsservice .
          docker images

#      - name: Setup .NET SDK
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: '8.0.101' # or the version you're using
#
#      - name: Restore dependencies
#        run: dotnet restore
#
#      - name: Build
#        run: dotnet build --configuration Release
