name: Build .NET App
  branch_name='refs/heads/none'
on:
  push:
    branches:
      - main
        
#-------------------------#        
permissions:
  id-token: write
  contents: read

#------------------------#

#------------------------#
jobs:
  build:
    runs-on: ubuntu-latest # Runner
    steps:
      
      # ------------------------------------- Checkout code -----------------------------------------
      - name: Checkout code
        uses: actions/checkout@v2
        if: github.ref == $branch_name
        
        
      - name: Build Docker image
        if: github.ref == $branch_name
        run: |
          docker build -t muhohoweb/tickets-service:1.0.5 .
          docker images

      #Login to docker Hub
      - name: Log in to Docker Hub
        if: github.ref == $branch_name
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Push image to docker hub
      - name: Push Docker image to Docker Hub
        if: github.ref == $branch_name
        run: |
          docker push muhohoweb/tickets-service:1.0.5

      # Convert key and Secret to files
      - name: Convert key and Secret to files
        if: github.ref == $branch_name
        run: |
          # Write client certificate to file
          echo "${{ secrets.VPN_CLIENT_CERT }}" > client.crt
          
          # Write client private key to file
          echo "${{ secrets.VPN_CLIENT_KEY }}" > client.key
          
          # Write OPEN_VPN private key to file
          echo "${{ secrets.OPEN_VPN }}" > config.ovpn
          
      
      # Install VPN    
      - name: Install OpenVPN
        if: github.ref == $branch_name
        run: |
            sudo apt-get update
            sudo apt-get --assume-yes --no-install-recommends install openvpn
            echo "${{ secrets.OPEN_VPN }}" > config.ovpn
            echo "${{ secrets.MAIN_KEY_PRIVATE }}" > main_key.pem
       
          
      # Connect to AWS VPN    
      - name: Connect VPN
        if: github.ref == $branch_name
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          PING_URL: '127.0.0.1'
          FILE_OVPN: config.ovpn
          SECRET: ${{ secrets.VPN_CLIENT_KEY }}
          TLS_KEY: ""
        env:
          CA_CRT: ${{ secrets.VPN_CA_CRT}}
          USER_CRT: ${{ secrets.VPN_CLIENT_CERT }}
          USER_KEY: ${{ secrets.VPN_CLIENT_KEY }}
      
      - name: Check Connect VPN
        if: github.ref == $branch_name
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}  
          
      - name: Ssh to private ec2
        if: github.ref == $branch_name
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: "10.0.141.195"
            key: ${{ secrets.MAIN_KEY_PRIVATE }}
            username: "ubuntu"
            port: 22
            script: | 
                  ls -la
              

      # Kill VPN connection        
      - name: kill vpn
        if: always()
        run: sudo killall openvpn
      
      # Azure Login 
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
        
      
      

